### ISSUE TITLE
Windows Blows

### ISSUE THREAD

**Issue by Demonstrandum** [trojan/Line-Out#1]
Linux support wen?

**Comment by b-coimbra** [comment]
oh, I forgot to mention Linux in the README (since no one would bother to play the game anyway)
I'm not sure if there's any special quirks that need to be done in order to run on Linux, but it should work fine for most web servers, try it out and let me know

**Comment by b-coimbra** [comment]
I forgot mongoose is available for Linux as well, so here you go: https://cesanta.com/
